import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    dashboard: 'Home',
    student_dashboard: 'Student Home',
    teacher_dashboard: 'Teacher Home',
    lectures: 'Lectures',
    quizzes: 'Quizzes',
    results: 'Results',
    flashcards: 'Flashcards',
    digital_skills: 'Digital Skills Basics',
    logout: 'Sign out',
    welcome: 'Welcome back',
    no_lectures: 'No lectures published yet.',
    available_lectures: 'Available lectures',
    download_lecture: 'DOWNLOAD LECTURE',
    take_quiz: 'Take Quiz',
    no_quizzes: 'No active quizzes.',
    create_quiz: 'Create Quiz',
    new_lecture: 'Upload New Lecture',
    title: 'Title',
    description: 'Description',
    skills_desc: 'Learn how to use a computer and the internet.',
    all: 'All',
    computer_science: 'Computer Science',
    mathematics: 'Mathematics',
    audio_resources: 'Audio Lectures',
    document_resources: 'Documents',
    no_videos_available: 'No video lectures available at the moment.',
    teacher_name: 'Teacher Name',
    subscribers: 'subscribers',
    published_on: 'Published on',
    no_description: 'No description provided',
    additional_resources: 'Additional Resources',
    audio_lecture_tag: 'Audio Lecture',
    document_file_tag: 'Document/File',
    download: 'Download',
    results_title: 'Your Results & Progress',
    results_subtitle: 'Track your performance across all quiz attempts.',
    loading_results: 'Loading results…',
    total_quizzes_attempted: 'Total Quizzes Attempted',
    total_submissions: 'Total Submissions',
    average_accuracy: 'Average Accuracy',
    attempt_history: 'Attempt History',
    no_attempts_results: "You haven't attempted any quizzes yet.",
    find_quizzes: 'Find Quizzes',
    excellent: 'Excellent',
    passed: 'Passed',
    needs_review: 'Needs Review',
    unknown_quiz: 'Unknown Quiz',
    questions_total: 'Questions Total',
    score_uppercase: 'SCORE',
    student_dashboard_subtitle: 'Pick a quiz, view lectures, or learn basics.',
    available_quizzes: 'Available quizzes',
    no_published_quizzes: 'No published quizzes yet.',
    seconds_time_limit: 's TIME LIMIT',
    recent_attempts: 'Recent attempts',
    no_attempts_recent: 'No attempts yet.',
    quiz: 'Quiz',
    click_to_flip: 'Click to flip',
    answer: 'Answer',
    flashcards_title: 'Flashcards',
    flashcards_subtitle: 'Generate a set from text, then practice by flipping cards.',
    your_sets: 'Your sets',
    no_sets: 'No sets yet.',
    delete_set: 'Delete Set',
    cards_count: 'cards',
    generate_new_set: 'Generate new set',
    set_title: 'Set title',
    topic_optional: 'Topic (optional)',
    paste_text: 'Paste text',
    generate_magic: 'GENERATE MAGIC',
    generating: 'GENERATING…',
    cards_ready: 'cards ready',
    save_set_btn: 'SAVE SET',
    delete_confirm_flashcard: 'Are you sure you want to delete this flashcard set?'
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    student_dashboard: 'ਵਿਦਿਆਰਥੀ ਡੈਸ਼ਬੋਰਡ',
    teacher_dashboard: 'ਅਧਿਆਪਕ ਡੈਸ਼ਬੋਰਡ',
    lectures: 'ਲੈਕਚਰ',
    quizzes: 'ਕਵਿਜ਼',
    results: 'ਨਤੀਜੇ',
    flashcards: 'ਫਲੈਸ਼ ਕਾਰਡ',
    digital_skills: 'ਡਿਜੀਟਲ ਹੁਨਰ (ਮੁੱਢਲੇ)',
    logout: 'ਸਾਈਨ ਆਉਟ',
    welcome: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    no_lectures: 'ਹਾਲੇ ਕੋਈ ਲੈਕਚਰ ਪ੍ਰਕਾਸ਼ਿਤ ਨਹੀਂ ਹੋਇਆ।',
    available_lectures: 'ਉਪਲਬਧ ਲੈਕਚਰ',
    download_lecture: 'ਲੈਕਚਰ ਡਾਊਨਲੋਡ ਕਰੋ',
    take_quiz: 'ਕਵਿਜ਼ ਸ਼ੁਰੂ ਕਰੋ',
    no_quizzes: 'ਕੋਈ ਸਰਗਰਮ ਕਵਿਜ਼ ਨਹੀਂ।',
    create_quiz: 'ਕਵਿਜ਼ ਬਣਾਓ',
    new_lecture: 'ਨਵਾਂ ਲੈਕਚਰ ਅੱਪਲੋਡ ਕਰੋ',
    title: 'ਸਿਰਲੇਖ',
    description: 'ਵੇਰਵਾ',
    skills_desc: 'ਕੰਪਿਊਟਰ ਅਤੇ ਇੰਟਰਨੈੱਟ ਦੀ ਵਰਤੋਂ ਕਰਨਾ ਸਿੱਖੋ।',
    all: 'ਸਾਰੇ',
    computer_science: 'ਕੰਪਿਊਟਰ ਸਾਇੰਸ',
    mathematics: 'ਗਣਿਤ',
    audio_resources: 'ਆਡੀਓ ਲੈਕਚਰ',
    document_resources: 'ਦਸਤਾਵੇਜ਼',
    no_videos_available: 'ਇਸ ਸਮੇਂ ਕੋਈ ਵੀਡੀਓ ਲੈਕਚਰ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
    teacher_name: 'ਅਧਿਆਪਕ ਦਾ ਨਾਮ',
    subscribers: 'ਸਬਸਕ੍ਰਾਈਬਰ',
    published_on: 'ਪ੍ਰਕਾਸ਼ਿਤ',
    no_description: 'ਕੋਈ ਵੇਰਵਾ ਨਹੀਂ ਦਿੱਤਾ ਗਿਆ',
    additional_resources: 'ਵਾਧੂ ਸਰੋਤ',
    audio_lecture_tag: 'ਆਡੀਓ ਲੈਕਚਰ',
    document_file_tag: 'ਦਸਤਾਵੇਜ਼/ਫਾਈਲ',
    download: 'ਡਾਊਨਲੋਡ',
    results_title: 'ਤੁਹਾਡੇ ਨਤੀਜੇ ਅਤੇ ਤਰੱਕੀ',
    results_subtitle: 'ਆਪਣੀਆਂ ਸਾਰੀਆਂ ਕਵਿਜ਼ ਕੋਸ਼ਿਸ਼ਾਂ ਵਿੱਚ ਆਪਣੇ ਪ੍ਰਦਰਸ਼ਨ ਨੂੰ ਟਰੈਕ ਕਰੋ।',
    loading_results: 'ਨਤੀਜੇ ਲੋਡ ਹੋ ਰਹੇ ਹਨ…',
    total_quizzes_attempted: 'ਕੁੱਲ ਕਵਿਜ਼ ਕੋਸ਼ਿਸ਼ਾਂ',
    total_submissions: 'ਕੁੱਲ ਜਮ੍ਹਾਂ',
    average_accuracy: 'ਔਸਤ ਸ਼ੁੱਧਤਾ',
    attempt_history: 'ਕੋਸ਼ਿਸ਼ ਦਾ ਇਤਿਹਾਸ',
    no_attempts_results: "ਤੁਸੀਂ ਹਾਲੇ ਤੱਕ ਕਿਸੇ ਕਵਿਜ਼ ਦੀ ਕੋਸ਼ਿਸ਼ ਨਹੀਂ ਕੀਤੀ ਹੈ।",
    find_quizzes: 'ਕਵਿਜ਼ ਲੱਭੋ',
    excellent: 'ਸ਼ਾਨਦਾਰ',
    passed: 'ਪਾਸ ਕੀਤਾ',
    needs_review: 'ਸਮੀਖਿਆ ਦੀ ਲੋੜ ਹੈ',
    unknown_quiz: 'ਅਣਜਾਣ ਕਵਿਜ਼',
    questions_total: 'ਕੁੱਲ ਪ੍ਰਸ਼ਨ',
    score_uppercase: 'ਅੰਕ',
    student_dashboard_subtitle: 'ਕੋਈ ਕਵਿਜ਼ ਚੁਣੋ, ਲੈਕਚਰ ਦੇਖੋ, ਜਾਂ ਬੁਨਿਆਦੀ ਗੱਲਾਂ ਸਿੱਖੋ।',
    available_quizzes: 'ਉਪਲਬਧ ਕਵਿਜ਼',
    no_published_quizzes: 'ਹਾਲੇ ਕੋਈ ਕਵਿਜ਼ ਪ੍ਰਕਾਸ਼ਿਤ ਨਹੀਂ ਹੋਇਆ।',
    seconds_time_limit: 'ਸਕਿੰਟ ਸਮਾਂ ਸੀਮਾ',
    recent_attempts: 'ਤਾਜ਼ਾ ਕੋਸ਼ਿਸ਼ਾਂ',
    no_attempts_recent: 'ਹਾਲੇ ਕੋਈ ਕੋਸ਼ਿਸ਼ ਨਹੀਂ।',
    quiz: 'ਕਵਿਜ਼',
    click_to_flip: 'ਪਲਟਣ ਲਈ ਕਲਿੱਕ ਕਰੋ',
    answer: 'ਜਵਾਬ',
    flashcards_title: 'ਫਲੈਸ਼ ਕਾਰਡ',
    flashcards_subtitle: 'ਟੈਕਸਟ ਤੋਂ ਇੱਕ ਸੈੱਟ ਬਣਾਓ, ਫਿਰ ਕਾਰਡ ਪਲਟ ਕੇ ਅਭਿਆਸ ਕਰੋ।',
    your_sets: 'ਤੁਹਾਡੇ ਸੈੱਟ',
    no_sets: 'ਹਾਲੇ ਕੋਈ ਸੈੱਟ ਨਹੀਂ।',
    delete_set: 'ਸੈੱਟ ਮਿਟਾਓ',
    cards_count: 'ਕਾਰਡ',
    generate_new_set: 'ਨਵਾਂ ਸੈੱਟ ਬਣਾਓ',
    set_title: 'ਸੈੱਟ ਦਾ ਸਿਰਲੇਖ',
    topic_optional: 'ਵਿਸ਼ਾ (ਵਿਕਲਪਿਕ)',
    paste_text: 'ਟੈਕਸਟ ਪੇਸਟ ਕਰੋ',
    generate_magic: 'ਜਾਦੂ ਬਣਾਓ',
    generating: 'ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ…',
    cards_ready: 'ਕਾਰਡ ਤਿਆਰ ਹਨ',
    save_set_btn: 'ਸੈੱਟ ਸੁਰੱਖਿਅਤ ਕਰੋ',
    delete_confirm_flashcard: 'ਕੀ ਤੁਸੀਂ ਯਕੀਨੀ ਹੋ ਕਿ ਤੁਸੀਂ ਇਸ ਫਲੈਸ਼ਕਾਰਡ ਸੈੱਟ ਨੂੰ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?'
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    student_dashboard: 'छात्र डैशबोर्ड',
    teacher_dashboard: 'शिक्षक डैशबोर्ड',
    lectures: 'व्याख्यान',
    quizzes: 'प्रश्नोत्तरी',
    results: 'परिणाम',
    flashcards: 'फ्लैशकार्ड',
    digital_skills: 'डिजिटल कौशल (मूल बातें)',
    logout: 'साइन आउट',
    welcome: 'वापसी पर स्वागत है',
    no_lectures: 'अभी तक कोई व्याख्यान प्रकाशित नहीं हुआ है।',
    available_lectures: 'उपलब्ध व्याख्यान',
    download_lecture: 'व्याख्यान डाउनलोड करें',
    take_quiz: 'प्रश्नोत्तरी लें',
    no_quizzes: 'कोई सक्रिय प्रश्नोत्तरी नहीं।',
    create_quiz: 'प्रश्नोत्तरी बनाएं',
    new_lecture: 'नया व्याख्यान अपलोड करें',
    title: 'शीर्षक',
    description: 'विवरण',
    skills_desc: 'कंप्यूटर और इंटरनेट का उपयोग करना सीखें।',
    all: 'सभी',
    computer_science: 'कंप्यूटर विज्ञान',
    mathematics: 'गणित',
    audio_resources: 'ऑडियो व्याख्यान',
    document_resources: 'दस्तावेज़',
    no_videos_available: 'फिलहाल कोई वीडियो व्याख्यान उपलब्ध नहीं है।',
    teacher_name: 'शिक्षक का नाम',
    subscribers: 'सब्सक्राइबर',
    published_on: 'प्रकाशित',
    no_description: 'कोई विवरण नहीं दिया गया',
    additional_resources: 'अतिरिक्त संसाधन',
    audio_lecture_tag: 'ऑडियो व्याख्यान',
    document_file_tag: 'दस्तावेज़/फ़ाइल',
    download: 'डाउनलोड',
    results_title: 'आपके परिणाम और प्रगति',
    results_subtitle: 'सभी प्रश्नोत्तरी प्रयासों में अपने प्रदर्शन को ट्रैक करें।',
    loading_results: 'परिणाम लोड हो रहे हैं…',
    total_quizzes_attempted: 'कुल प्रश्नोत्तरी प्रयास',
    total_submissions: 'कुल सबमिशन',
    average_accuracy: 'औसत सटीकता',
    attempt_history: 'प्रयास का इतिहास',
    no_attempts_results: "आपने अभी तक किसी भी प्रश्नोत्तरी का प्रयास नहीं किया है।",
    find_quizzes: 'प्रश्नोत्तरी खोजें',
    excellent: 'उत्कृष्ट',
    passed: 'उत्तीर्ण',
    needs_review: 'समीक्षा की आवश्यकता है',
    unknown_quiz: 'अज्ञात प्रश्नोत्तरी',
    questions_total: 'कुल प्रश्न',
    score_uppercase: 'स्कोर',
    student_dashboard_subtitle: 'एक प्रश्नोत्तरी चुनें, व्याख्यान देखें, या मूल बातें सीखें।',
    available_quizzes: 'उपलब्ध प्रश्नोत्तरी',
    no_published_quizzes: 'अभी तक कोई प्रश्नोत्तरी प्रकाशित नहीं हुई है।',
    seconds_time_limit: 'सेकंड समय सीमा',
    recent_attempts: 'हाल के प्रयास',
    no_attempts_recent: 'अभी तक कोई प्रयास नहीं।',
    quiz: 'प्रश्नोत्तरी',
    click_to_flip: 'पलटने के लिए क्लिक करें',
    answer: 'उत्तर',
    flashcards_title: 'फ्लैशकार्ड',
    flashcards_subtitle: 'टेक्स्ट से एक सेट जेनरेट करें, फिर कार्ड पलटकर अभ्यास करें।',
    your_sets: 'आपके सेट',
    no_sets: 'अभी तक कोई सेट नहीं।',
    delete_set: 'सेट हटाएं',
    cards_count: 'कार्ड',
    generate_new_set: 'नया सेट बनाएं',
    set_title: 'सेट का शीर्षक',
    topic_optional: 'विषय (वैकल्पिक)',
    paste_text: 'टेक्स्ट पेस्ट करें',
    generate_magic: 'जादू उत्पन्न करें',
    generating: 'उत्पन्न हो रहा है…',
    cards_ready: 'कार्ड तैयार हैं',
    save_set_btn: 'सेट सेव करें',
    delete_confirm_flashcard: 'क्या आप निश्चित हैं कि आप इस फ्लैशकार्ड सेट को हटाना चाहते हैं?'
  }
};

export function LanguageProvider({ children }) {
  // Load language from localStorage or default to English
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('appLanguage');
    return saved && translations[saved] ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
    // Optionally set document dir/lang attributes
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    // Return translation if exists, otherwise fallback to english, then the key itself
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
