import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

// ── English (base) ────────────────────────────────────────────────────────────
const en = {
  dashboard: 'Home', student_dashboard: 'Student Home', teacher_dashboard: 'Teacher Home',
  lectures: 'Lectures', quizzes: 'Quizzes', results: 'Results', flashcards: 'Flashcards',
  digital_skills: 'Digital Skills Basics', logout: 'Sign out', welcome: 'Welcome back',
  no_lectures: 'No lectures published yet.', available_lectures: 'Available lectures',
  download_lecture: 'DOWNLOAD LECTURE', take_quiz: 'Take Quiz', no_quizzes: 'No active quizzes.',
  create_quiz: 'Create Quiz', new_lecture: 'Upload New Lecture', title: 'Title', description: 'Description',
  skills_desc: 'Learn how to use a computer and the internet.', all: 'All',
  computer_science: 'Computer Science', mathematics: 'Mathematics',
  audio_resources: 'Audio Lectures', document_resources: 'Documents',
  no_videos_available: 'No video lectures available at the moment.',
  teacher_name: 'Teacher Name', subscribers: 'subscribers', published_on: 'Published on',
  no_description: 'No description provided', additional_resources: 'Additional Resources',
  audio_lecture_tag: 'Audio Lecture', document_file_tag: 'Document/File', download: 'Download',
  results_title: 'Your Results & Progress', results_subtitle: 'Track your performance across all quiz attempts.',
  loading_results: 'Loading results…', total_quizzes_attempted: 'Total Quizzes Attempted',
  total_submissions: 'Total Submissions', average_accuracy: 'Average Accuracy',
  attempt_history: 'Attempt History', no_attempts_results: "You haven't attempted any quizzes yet.",
  find_quizzes: 'Find Quizzes', excellent: 'Excellent', passed: 'Passed', needs_review: 'Needs Review',
  unknown_quiz: 'Unknown Quiz', questions_total: 'Questions Total', score_uppercase: 'SCORE',
  student_dashboard_subtitle: 'Pick a quiz, view lectures, or learn basics.',
  available_quizzes: 'Available quizzes', no_published_quizzes: 'No published quizzes yet.',
  seconds_time_limit: 's TIME LIMIT', recent_attempts: 'Recent attempts', no_attempts_recent: 'No attempts yet.',
  quiz: 'Quiz', click_to_flip: 'Click to flip', answer: 'Answer',
  flashcards_title: 'Flashcards', flashcards_subtitle: 'Generate a set from text, then practice by flipping cards.',
  your_sets: 'Your sets', no_sets: 'No sets yet.', delete_set: 'Delete Set', cards_count: 'cards',
  generate_new_set: 'Generate new set', set_title: 'Set title', topic_optional: 'Topic (optional)',
  paste_text: 'Paste text', generate_magic: 'GENERATE MAGIC', generating: 'GENERATING…',
  cards_ready: 'cards ready', save_set_btn: 'SAVE SET',
  delete_confirm_flashcard: 'Are you sure you want to delete this flashcard set?',
  // Attendance
  attendance: 'Attendance', mark_attendance: 'Mark Attendance', register_student: 'Register Student',
  records: 'Records', manage_classes: 'Manage Classes', scanning: 'Scanning…',
  capture_btn: 'Capture & Mark Attendance', processing: 'Processing…',
  total_days: 'Total Days', present: 'Present', absent: 'Absent', attendance_pct: 'Attendance %',
  select_class_section: 'Select Class Section', choose_class: '— Choose a class section —',
  no_classes_found: 'No classes found.', look_at_camera: 'Look directly at the camera with your face well-lit, then click capture.',
  select_student: 'Select Student', choose_student: '— Choose a registered student —',
  start_capture: 'Start Capture', stop_recording: 'Stop', upload_frames: 'Upload Frames',
  student_summary: 'Student Summary', no_records_found: 'No records found.', loading_records: 'Loading records…',
  // Scholarships
  scholarships: 'Scholarships', scholarships_title: 'Unlock Your Potential with Scholarships',
  scholarships_subtitle: 'Explore carefully curated financial aid opportunities tailored for school students.',
  no_scholarships: 'No scholarships available at the moment. Please check back later!',
  deadline: 'Deadline', eligibility: 'Eligibility', amount: 'Amount', apply_now: 'Apply Now',
  // Quiz pages
  quiz_complete: 'Quiz Complete', your_score: 'Your score', back_to_dashboard: 'Back to Dashboard',
  view_quiz_details: 'View Quiz Details', loading_quiz: 'Loading quiz…',
  submit_answers: 'Submit Answers', submitting: 'Submitting…', question_label: 'Question',
  questions_count: 'Questions', time_limit: 'Time Limit', start_quiz: 'Start Quiz',
  quiz_completed_badge: 'Quiz Completed', already_attempted: 'You have already attempted this quiz.',
  loading_quiz_details: 'Loading quiz details…', review: 'Review',
};

// ── Hindi ─────────────────────────────────────────────────────────────────────
const hi = {
  dashboard: 'होम', student_dashboard: 'छात्र होम', teacher_dashboard: 'शिक्षक होम',
  lectures: 'व्याख्यान', quizzes: 'प्रश्नोत्तरी', results: 'परिणाम', flashcards: 'फ्लैशकार्ड',
  digital_skills: 'डिजिटल कौशल', logout: 'साइन आउट', welcome: 'वापसी पर स्वागत है',
  no_lectures: 'अभी कोई व्याख्यान नहीं।', available_lectures: 'उपलब्ध व्याख्यान',
  download_lecture: 'व्याख्यान डाउनलोड करें', take_quiz: 'प्रश्नोत्तरी लें', no_quizzes: 'कोई प्रश्नोत्तरी नहीं।',
  create_quiz: 'प्रश्नोत्तरी बनाएं', new_lecture: 'नया व्याख्यान अपलोड करें', title: 'शीर्षक', description: 'विवरण',
  skills_desc: 'कंप्यूटर और इंटरनेट का उपयोग सीखें।', all: 'सभी',
  computer_science: 'कंप्यूटर विज्ञान', mathematics: 'गणित',
  audio_resources: 'ऑडियो व्याख्यान', document_resources: 'दस्तावेज़',
  no_videos_available: 'कोई वीडियो उपलब्ध नहीं।', teacher_name: 'शिक्षक का नाम',
  subscribers: 'सब्सक्राइबर', published_on: 'प्रकाशित', no_description: 'कोई विवरण नहीं',
  additional_resources: 'अतिरिक्त संसाधन', audio_lecture_tag: 'ऑडियो व्याख्यान',
  document_file_tag: 'दस्तावेज़/फ़ाइल', download: 'डाउनलोड',
  results_title: 'आपके परिणाम', results_subtitle: 'सभी प्रयासों में प्रदर्शन ट्रैक करें।',
  loading_results: 'परिणाम लोड हो रहे हैं…', total_quizzes_attempted: 'कुल प्रश्नोत्तरी प्रयास',
  total_submissions: 'कुल सबमिशन', average_accuracy: 'औसत सटीकता',
  attempt_history: 'प्रयास इतिहास', no_attempts_results: 'अभी तक कोई प्रयास नहीं।',
  find_quizzes: 'प्रश्नोत्तरी खोजें', excellent: 'उत्कृष्ट', passed: 'उत्तीर्ण', needs_review: 'समीक्षा आवश्यक',
  unknown_quiz: 'अज्ञात प्रश्नोत्तरी', questions_total: 'कुल प्रश्न', score_uppercase: 'स्कोर',
  student_dashboard_subtitle: 'प्रश्नोत्तरी चुनें, व्याख्यान देखें।',
  available_quizzes: 'उपलब्ध प्रश्नोत्तरी', no_published_quizzes: 'कोई प्रश्नोत्तरी नहीं।',
  seconds_time_limit: 'सेकंड समय सीमा', recent_attempts: 'हाल के प्रयास', no_attempts_recent: 'कोई प्रयास नहीं।',
  quiz: 'प्रश्नोत्तरी', click_to_flip: 'पलटने के लिए क्लिक करें', answer: 'उत्तर',
  flashcards_title: 'फ्लैशकार्ड', flashcards_subtitle: 'टेक्स्ट से सेट बनाएं और अभ्यास करें।',
  your_sets: 'आपके सेट', no_sets: 'कोई सेट नहीं।', delete_set: 'सेट हटाएं', cards_count: 'कार्ड',
  generate_new_set: 'नया सेट बनाएं', set_title: 'सेट शीर्षक', topic_optional: 'विषय (वैकल्पिक)',
  paste_text: 'टेक्स्ट पेस्ट करें', generate_magic: 'जादू उत्पन्न करें', generating: 'उत्पन्न हो रहा है…',
  cards_ready: 'कार्ड तैयार', save_set_btn: 'सेट सेव करें',
  delete_confirm_flashcard: 'क्या आप इस फ्लैशकार्ड सेट को हटाना चाहते हैं?',
  attendance: 'उपस्थिति', mark_attendance: 'उपस्थिति दर्ज करें', register_student: 'छात्र पंजीकृत करें',
  records: 'रिकॉर्ड', manage_classes: 'कक्षाएं प्रबंधित करें', scanning: 'स्कैन हो रहा है…',
  capture_btn: 'कैप्चर करें और उपस्थिति दर्ज करें', processing: 'प्रोसेस हो रहा है…',
  total_days: 'कुल दिन', present: 'उपस्थित', absent: 'अनुपस्थित', attendance_pct: 'उपस्थिति %',
  select_class_section: 'कक्षा चुनें', choose_class: '— कक्षा चुनें —',
  no_classes_found: 'कोई कक्षा नहीं मिली।', look_at_camera: 'कैमरे की ओर देखें और कैप्चर करें।',
  select_student: 'छात्र चुनें', choose_student: '— छात्र चुनें —',
  start_capture: 'कैप्चर शुरू करें', stop_recording: 'रोकें', upload_frames: 'फ्रेम अपलोड करें',
  student_summary: 'छात्र सारांश', no_records_found: 'कोई रिकॉर्ड नहीं।', loading_records: 'रिकॉर्ड लोड हो रहे हैं…',
  scholarships: 'छात्रवृत्ति', scholarships_title: 'छात्रवृत्ति से अपनी क्षमता उजागर करें',
  scholarships_subtitle: 'स्कूली छात्रों के लिए वित्तीय सहायता के अवसर।',
  no_scholarships: 'अभी कोई छात्रवृत्ति उपलब्ध नहीं।',
  deadline: 'अंतिम तिथि', eligibility: 'पात्रता', amount: 'राशि', apply_now: 'अभी आवेदन करें',
  quiz_complete: 'प्रश्नोत्तरी पूर्ण', your_score: 'आपका स्कोर', back_to_dashboard: 'डैशबोर्ड पर वापस',
  view_quiz_details: 'प्रश्नोत्तरी विवरण देखें', loading_quiz: 'प्रश्नोत्तरी लोड हो रही है…',
  submit_answers: 'उत्तर जमा करें', submitting: 'जमा हो रहा है…', question_label: 'प्रश्न',
  questions_count: 'प्रश्न', time_limit: 'समय सीमा', start_quiz: 'प्रश्नोत्तरी शुरू करें',
  quiz_completed_badge: 'प्रश्नोत्तरी पूर्ण', already_attempted: 'आप पहले ही यह प्रश्नोत्तरी दे चुके हैं।',
  loading_quiz_details: 'विवरण लोड हो रहा है…', review: 'समीक्षा',
};

// ── Punjabi ───────────────────────────────────────────────────────────────────
const pa = {
  dashboard: 'ਹੋਮ', student_dashboard: 'ਵਿਦਿਆਰਥੀ ਹੋਮ', teacher_dashboard: 'ਅਧਿਆਪਕ ਹੋਮ',
  lectures: 'ਲੈਕਚਰ', quizzes: 'ਕਵਿਜ਼', results: 'ਨਤੀਜੇ', flashcards: 'ਫਲੈਸ਼ ਕਾਰਡ',
  digital_skills: 'ਡਿਜੀਟਲ ਹੁਨਰ', logout: 'ਸਾਈਨ ਆਉਟ', welcome: 'ਜੀ ਆਇਆਂ ਨੂੰ',
  no_lectures: 'ਕੋਈ ਲੈਕਚਰ ਨਹੀਂ।', available_lectures: 'ਉਪਲਬਧ ਲੈਕਚਰ',
  download_lecture: 'ਲੈਕਚਰ ਡਾਊਨਲੋਡ ਕਰੋ', take_quiz: 'ਕਵਿਜ਼ ਸ਼ੁਰੂ ਕਰੋ', no_quizzes: 'ਕੋਈ ਕਵਿਜ਼ ਨਹੀਂ।',
  create_quiz: 'ਕਵਿਜ਼ ਬਣਾਓ', new_lecture: 'ਨਵਾਂ ਲੈਕਚਰ ਅੱਪਲੋਡ ਕਰੋ', title: 'ਸਿਰਲੇਖ', description: 'ਵੇਰਵਾ',
  skills_desc: 'ਕੰਪਿਊਟਰ ਅਤੇ ਇੰਟਰਨੈੱਟ ਸਿੱਖੋ।', all: 'ਸਾਰੇ',
  computer_science: 'ਕੰਪਿਊਟਰ ਸਾਇੰਸ', mathematics: 'ਗਣਿਤ',
  audio_resources: 'ਆਡੀਓ ਲੈਕਚਰ', document_resources: 'ਦਸਤਾਵੇਜ਼',
  no_videos_available: 'ਕੋਈ ਵੀਡੀਓ ਉਪਲਬਧ ਨਹੀਂ।', teacher_name: 'ਅਧਿਆਪਕ ਦਾ ਨਾਮ',
  subscribers: 'ਸਬਸਕ੍ਰਾਈਬਰ', published_on: 'ਪ੍ਰਕਾਸ਼ਿਤ', no_description: 'ਕੋਈ ਵੇਰਵਾ ਨਹੀਂ',
  additional_resources: 'ਵਾਧੂ ਸਰੋਤ', audio_lecture_tag: 'ਆਡੀਓ ਲੈਕਚਰ',
  document_file_tag: 'ਦਸਤਾਵੇਜ਼/ਫਾਈਲ', download: 'ਡਾਊਨਲੋਡ',
  results_title: 'ਤੁਹਾਡੇ ਨਤੀਜੇ', results_subtitle: 'ਆਪਣੇ ਪ੍ਰਦਰਸ਼ਨ ਨੂੰ ਟਰੈਕ ਕਰੋ।',
  loading_results: 'ਨਤੀਜੇ ਲੋਡ ਹੋ ਰਹੇ ਹਨ…', total_quizzes_attempted: 'ਕੁੱਲ ਕਵਿਜ਼ ਕੋਸ਼ਿਸ਼ਾਂ',
  total_submissions: 'ਕੁੱਲ ਜਮ੍ਹਾਂ', average_accuracy: 'ਔਸਤ ਸ਼ੁੱਧਤਾ',
  attempt_history: 'ਕੋਸ਼ਿਸ਼ ਇਤਿਹਾਸ', no_attempts_results: 'ਅਜੇ ਕੋਈ ਕੋਸ਼ਿਸ਼ ਨਹੀਂ।',
  find_quizzes: 'ਕਵਿਜ਼ ਲੱਭੋ', excellent: 'ਸ਼ਾਨਦਾਰ', passed: 'ਪਾਸ', needs_review: 'ਸਮੀਖਿਆ ਲੋੜੀਂਦੀ',
  unknown_quiz: 'ਅਣਜਾਣ ਕਵਿਜ਼', questions_total: 'ਕੁੱਲ ਪ੍ਰਸ਼ਨ', score_uppercase: 'ਅੰਕ',
  student_dashboard_subtitle: 'ਕਵਿਜ਼ ਚੁਣੋ, ਲੈਕਚਰ ਦੇਖੋ।',
  available_quizzes: 'ਉਪਲਬਧ ਕਵਿਜ਼', no_published_quizzes: 'ਕੋਈ ਕਵਿਜ਼ ਨਹੀਂ।',
  seconds_time_limit: 'ਸਕਿੰਟ ਸਮਾਂ ਸੀਮਾ', recent_attempts: 'ਤਾਜ਼ਾ ਕੋਸ਼ਿਸ਼ਾਂ', no_attempts_recent: 'ਕੋਈ ਕੋਸ਼ਿਸ਼ ਨਹੀਂ।',
  quiz: 'ਕਵਿਜ਼', click_to_flip: 'ਪਲਟਣ ਲਈ ਕਲਿੱਕ ਕਰੋ', answer: 'ਜਵਾਬ',
  flashcards_title: 'ਫਲੈਸ਼ ਕਾਰਡ', flashcards_subtitle: 'ਟੈਕਸਟ ਤੋਂ ਸੈੱਟ ਬਣਾਓ।',
  your_sets: 'ਤੁਹਾਡੇ ਸੈੱਟ', no_sets: 'ਕੋਈ ਸੈੱਟ ਨਹੀਂ।', delete_set: 'ਸੈੱਟ ਮਿਟਾਓ', cards_count: 'ਕਾਰਡ',
  generate_new_set: 'ਨਵਾਂ ਸੈੱਟ ਬਣਾਓ', set_title: 'ਸੈੱਟ ਸਿਰਲੇਖ', topic_optional: 'ਵਿਸ਼ਾ (ਵਿਕਲਪਿਕ)',
  paste_text: 'ਟੈਕਸਟ ਪੇਸਟ ਕਰੋ', generate_magic: 'ਜਾਦੂ ਬਣਾਓ', generating: 'ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ…',
  cards_ready: 'ਕਾਰਡ ਤਿਆਰ', save_set_btn: 'ਸੈੱਟ ਸੁਰੱਖਿਅਤ ਕਰੋ',
  delete_confirm_flashcard: 'ਕੀ ਤੁਸੀਂ ਇਸ ਫਲੈਸ਼ਕਾਰਡ ਸੈੱਟ ਨੂੰ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?',
  attendance: 'ਹਾਜ਼ਰੀ', mark_attendance: 'ਹਾਜ਼ਰੀ ਦਰਜ ਕਰੋ', register_student: 'ਵਿਦਿਆਰਥੀ ਰਜਿਸਟਰ ਕਰੋ',
  records: 'ਰਿਕਾਰਡ', manage_classes: 'ਕਲਾਸਾਂ ਪ੍ਰਬੰਧਿਤ ਕਰੋ', scanning: 'ਸਕੈਨ ਹੋ ਰਿਹਾ ਹੈ…',
  capture_btn: 'ਕੈਪਚਰ ਕਰੋ ਅਤੇ ਹਾਜ਼ਰੀ ਦਰਜ ਕਰੋ', processing: 'ਪ੍ਰੋਸੈਸ ਹੋ ਰਿਹਾ ਹੈ…',
  total_days: 'ਕੁੱਲ ਦਿਨ', present: 'ਹਾਜ਼ਰ', absent: 'ਗੈਰਹਾਜ਼ਰ', attendance_pct: 'ਹਾਜ਼ਰੀ %',
  select_class_section: 'ਕਲਾਸ ਚੁਣੋ', choose_class: '— ਕਲਾਸ ਚੁਣੋ —',
  no_classes_found: 'ਕੋਈ ਕਲਾਸ ਨਹੀਂ ਮਿਲੀ।', look_at_camera: 'ਕੈਮਰੇ ਵੱਲ ਦੇਖੋ ਅਤੇ ਕੈਪਚਰ ਕਰੋ।',
  select_student: 'ਵਿਦਿਆਰਥੀ ਚੁਣੋ', choose_student: '— ਵਿਦਿਆਰਥੀ ਚੁਣੋ —',
  start_capture: 'ਕੈਪਚਰ ਸ਼ੁਰੂ ਕਰੋ', stop_recording: 'ਰੋਕੋ', upload_frames: 'ਫ੍ਰੇਮ ਅਪਲੋਡ ਕਰੋ',
  student_summary: 'ਵਿਦਿਆਰਥੀ ਸਾਰਾਂਸ਼', no_records_found: 'ਕੋਈ ਰਿਕਾਰਡ ਨਹੀਂ।', loading_records: 'ਰਿਕਾਰਡ ਲੋਡ ਹੋ ਰਹੇ ਹਨ…',
  scholarships: 'ਵਜ਼ੀਫ਼ੇ', scholarships_title: 'ਵਜ਼ੀਫ਼ਿਆਂ ਨਾਲ ਆਪਣੀ ਸੰਭਾਵਨਾ ਖੋਲ੍ਹੋ',
  scholarships_subtitle: 'ਵਿਦਿਆਰਥੀਆਂ ਲਈ ਵਿੱਤੀ ਸਹਾਇਤਾ ਦੇ ਮੌਕੇ।',
  no_scholarships: 'ਹੁਣੇ ਕੋਈ ਵਜ਼ੀਫ਼ਾ ਉਪਲਬਧ ਨਹੀਂ।',
  deadline: 'ਆਖਰੀ ਮਿਤੀ', eligibility: 'ਯੋਗਤਾ', amount: 'ਰਕਮ', apply_now: 'ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ',
  quiz_complete: 'ਕਵਿਜ਼ ਪੂਰੀ', your_score: 'ਤੁਹਾਡਾ ਸਕੋਰ', back_to_dashboard: 'ਡੈਸ਼ਬੋਰਡ ਤੇ ਵਾਪਸ',
  view_quiz_details: 'ਕਵਿਜ਼ ਵੇਰਵੇ ਦੇਖੋ', loading_quiz: 'ਕਵਿਜ਼ ਲੋਡ ਹੋ ਰਹੀ ਹੈ…',
  submit_answers: 'ਜਵਾਬ ਜਮ੍ਹਾਂ ਕਰੋ', submitting: 'ਜਮ੍ਹਾਂ ਹੋ ਰਿਹਾ ਹੈ…', question_label: 'ਪ੍ਰਸ਼ਨ',
  questions_count: 'ਪ੍ਰਸ਼ਨ', time_limit: 'ਸਮਾਂ ਸੀਮਾ', start_quiz: 'ਕਵਿਜ਼ ਸ਼ੁਰੂ ਕਰੋ',
  quiz_completed_badge: 'ਕਵਿਜ਼ ਪੂਰੀ', already_attempted: 'ਤੁਸੀਂ ਪਹਿਲਾਂ ਹੀ ਇਹ ਕਵਿਜ਼ ਦੇ ਚੁੱਕੇ ਹੋ।',
  loading_quiz_details: 'ਵੇਰਵੇ ਲੋਡ ਹੋ ਰਹੇ ਹਨ…', review: 'ਸਮੀਖਿਆ',
};

// ── Bengali ───────────────────────────────────────────────────────────────────
const bn = {
  dashboard: 'হোম', student_dashboard: 'ছাত্র হোম', teacher_dashboard: 'শিক্ষক হোম',
  lectures: 'বক্তৃতা', quizzes: 'কুইজ', results: 'ফলাফল', flashcards: 'ফ্ল্যাশকার্ড',
  digital_skills: 'ডিজিটাল দক্ষতা', logout: 'সাইন আউট', welcome: 'স্বাগতম',
  no_lectures: 'কোনো বক্তৃতা নেই।', available_lectures: 'উপলব্ধ বক্তৃতা',
  download_lecture: 'বক্তৃতা ডাউনলোড করুন', take_quiz: 'কুইজ দিন', no_quizzes: 'কোনো কুইজ নেই।',
  create_quiz: 'কুইজ তৈরি করুন', new_lecture: 'নতুন বক্তৃতা আপলোড করুন', title: 'শিরোনাম', description: 'বিবরণ',
  skills_desc: 'কম্পিউটার ও ইন্টারনেট ব্যবহার শিখুন।', all: 'সব',
  computer_science: 'কম্পিউটার বিজ্ঞান', mathematics: 'গণিত',
  audio_resources: 'অডিও বক্তৃতা', document_resources: 'নথি',
  no_videos_available: 'কোনো ভিডিও নেই।', teacher_name: 'শিক্ষকের নাম',
  subscribers: 'সাবস্ক্রাইবার', published_on: 'প্রকাশিত', no_description: 'কোনো বিবরণ নেই',
  additional_resources: 'অতিরিক্ত সম্পদ', audio_lecture_tag: 'অডিও বক্তৃতা',
  document_file_tag: 'নথি/ফাইল', download: 'ডাউনলোড',
  results_title: 'আপনার ফলাফল', results_subtitle: 'সমস্ত কুইজ প্রচেষ্টায় পারফরম্যান্স ট্র্যাক করুন।',
  loading_results: 'ফলাফল লোড হচ্ছে…', total_quizzes_attempted: 'মোট কুইজ প্রচেষ্টা',
  total_submissions: 'মোট জমা', average_accuracy: 'গড় নির্ভুলতা',
  attempt_history: 'প্রচেষ্টার ইতিহাস', no_attempts_results: 'এখনো কোনো প্রচেষ্টা নেই।',
  find_quizzes: 'কুইজ খুঁজুন', excellent: 'চমৎকার', passed: 'পাস', needs_review: 'পর্যালোচনা প্রয়োজন',
  unknown_quiz: 'অজানা কুইজ', questions_total: 'মোট প্রশ্ন', score_uppercase: 'স্কোর',
  student_dashboard_subtitle: 'কুইজ বেছে নিন, বক্তৃতা দেখুন।',
  available_quizzes: 'উপলব্ধ কুইজ', no_published_quizzes: 'কোনো কুইজ নেই।',
  seconds_time_limit: 'সেকেন্ড সময়সীমা', recent_attempts: 'সাম্প্রতিক প্রচেষ্টা', no_attempts_recent: 'কোনো প্রচেষ্টা নেই।',
  quiz: 'কুইজ', click_to_flip: 'উল্টাতে ক্লিক করুন', answer: 'উত্তর',
  flashcards_title: 'ফ্ল্যাশকার্ড', flashcards_subtitle: 'টেক্সট থেকে সেট তৈরি করুন।',
  your_sets: 'আপনার সেট', no_sets: 'কোনো সেট নেই।', delete_set: 'সেট মুছুন', cards_count: 'কার্ড',
  generate_new_set: 'নতুন সেট তৈরি করুন', set_title: 'সেট শিরোনাম', topic_optional: 'বিষয় (ঐচ্ছিক)',
  paste_text: 'টেক্সট পেস্ট করুন', generate_magic: 'জাদু তৈরি করুন', generating: 'তৈরি হচ্ছে…',
  cards_ready: 'কার্ড প্রস্তুত', save_set_btn: 'সেট সংরক্ষণ করুন',
  delete_confirm_flashcard: 'আপনি কি এই ফ্ল্যাশকার্ড সেটটি মুছতে চান?',
  attendance: 'উপস্থিতি', mark_attendance: 'উপস্থিতি চিহ্নিত করুন', register_student: 'ছাত্র নিবন্ধন করুন',
  records: 'রেকর্ড', manage_classes: 'ক্লাস পরিচালনা করুন', scanning: 'স্ক্যান হচ্ছে…',
  capture_btn: 'ক্যাপচার করুন এবং উপস্থিতি চিহ্নিত করুন', processing: 'প্রক্রিয়া হচ্ছে…',
  total_days: 'মোট দিন', present: 'উপস্থিত', absent: 'অনুপস্থিত', attendance_pct: 'উপস্থিতি %',
  select_class_section: 'ক্লাস বিভাগ নির্বাচন করুন', choose_class: '— ক্লাস বিভাগ বেছে নিন —',
  no_classes_found: 'কোনো ক্লাস পাওয়া যায়নি।', look_at_camera: 'ক্যামেরার দিকে তাকান এবং ক্যাপচার করুন।',
  select_student: 'ছাত্র নির্বাচন করুন', choose_student: '— নিবন্ধিত ছাত্র বেছে নিন —',
  start_capture: 'ক্যাপচার শুরু করুন', stop_recording: 'থামুন', upload_frames: 'ফ্রেম আপলোড করুন',
  student_summary: 'ছাত্র সারসংক্ষেপ', no_records_found: 'কোনো রেকর্ড পাওয়া যায়নি।', loading_records: 'রেকর্ড লোড হচ্ছে…',
  scholarships: 'বৃত্তি', scholarships_title: 'বৃত্তির মাধ্যমে আপনার সম্ভাবনা উন্মুক্ত করুন',
  scholarships_subtitle: 'স্কুল ছাত্রদের জন্য আর্থিক সহায়তার সুযোগ।',
  no_scholarships: 'এই মুহূর্তে কোনো বৃত্তি নেই।',
  deadline: 'শেষ তারিখ', eligibility: 'যোগ্যতা', amount: 'পরিমাণ', apply_now: 'এখনই আবেদন করুন',
  quiz_complete: 'কুইজ সম্পন্ন', your_score: 'আপনার স্কোর', back_to_dashboard: 'ড্যাশবোর্ডে ফিরুন',
  view_quiz_details: 'কুইজ বিবরণ দেখুন', loading_quiz: 'কুইজ লোড হচ্ছে…',
  submit_answers: 'উত্তর জমা দিন', submitting: 'জমা হচ্ছে…', question_label: 'প্রশ্ন',
  questions_count: 'প্রশ্ন', time_limit: 'সময়সীমা', start_quiz: 'কুইজ শুরু করুন',
  quiz_completed_badge: 'কুইজ সম্পন্ন', already_attempted: 'আপনি ইতিমধ্যে এই কুইজটি দিয়েছেন।',
  loading_quiz_details: 'বিবরণ লোড হচ্ছে…', review: 'পর্যালোচনা',
};

// ── Telugu ────────────────────────────────────────────────────────────────────
const te = {
  dashboard: 'హోమ్', student_dashboard: 'విద్యార్థి హోమ్', teacher_dashboard: 'ఉపాధ్యాయుడి హోమ్',
  lectures: 'ఉపన్యాసాలు', quizzes: 'క్విజ్‌లు', results: 'ఫలితాలు', flashcards: 'ఫ్లాష్‌కార్డ్‌లు',
  digital_skills: 'డిజిటల్ నైపుణ్యాలు', logout: 'సైన్ అవుట్', welcome: 'స్వాగతం',
  no_lectures: 'ఉపన్యాసాలు లేవు.', available_lectures: 'అందుబాటులో ఉన్న ఉపన్యాసాలు',
  download_lecture: 'ఉపన్యాసం డౌన్‌లోడ్ చేయండి', take_quiz: 'క్విజ్ తీసుకోండి', no_quizzes: 'క్విజ్‌లు లేవు.',
  create_quiz: 'క్విజ్ సృష్టించండి', new_lecture: 'కొత్త ఉపన్యాసం అప్‌లోడ్ చేయండి', title: 'శీర్షిక', description: 'వివరణ',
  skills_desc: 'కంప్యూటర్ మరియు ఇంటర్నెట్ ఉపయోగించడం నేర్చుకోండి.', all: 'అన్నీ',
  computer_science: 'కంప్యూటర్ సైన్స్', mathematics: 'గణితం',
  audio_resources: 'ఆడియో ఉపన్యాసాలు', document_resources: 'పత్రాలు',
  no_videos_available: 'వీడియోలు లేవు.', teacher_name: 'ఉపాధ్యాయుని పేరు',
  subscribers: 'సబ్‌స్క్రైబర్లు', published_on: 'ప్రచురించబడింది', no_description: 'వివరణ లేదు',
  additional_resources: 'అదనపు వనరులు', audio_lecture_tag: 'ఆడియో ఉపన్యాసం',
  document_file_tag: 'పత్రం/ఫైల్', download: 'డౌన్‌లోడ్',
  results_title: 'మీ ఫలితాలు', results_subtitle: 'మీ పనితీరును ట్రాక్ చేయండి.',
  loading_results: 'ఫలితాలు లోడ్ అవుతున్నాయి…', total_quizzes_attempted: 'మొత్తం క్విజ్ ప్రయత్నాలు',
  total_submissions: 'మొత్తం సమర్పణలు', average_accuracy: 'సగటు ఖచ్చితత్వం',
  attempt_history: 'ప్రయత్న చరిత్ర', no_attempts_results: 'ఇంకా ప్రయత్నాలు లేవు.',
  find_quizzes: 'క్విజ్‌లు కనుగొనండి', excellent: 'అద్భుతం', passed: 'పాస్', needs_review: 'సమీక్ష అవసరం',
  unknown_quiz: 'తెలియని క్విజ్', questions_total: 'మొత్తం ప్రశ్నలు', score_uppercase: 'స్కోర్',
  student_dashboard_subtitle: 'క్విజ్ ఎంచుకోండి, ఉపన్యాసాలు చూడండి.',
  available_quizzes: 'అందుబాటులో ఉన్న క్విజ్‌లు', no_published_quizzes: 'క్విజ్‌లు లేవు.',
  seconds_time_limit: 'సెకన్ల సమయ పరిమితి', recent_attempts: 'ఇటీవలి ప్రయత్నాలు', no_attempts_recent: 'ప్రయత్నాలు లేవు.',
  quiz: 'క్విజ్', click_to_flip: 'తిప్పడానికి క్లిక్ చేయండి', answer: 'సమాధానం',
  flashcards_title: 'ఫ్లాష్‌కార్డ్‌లు', flashcards_subtitle: 'టెక్స్ట్ నుండి సెట్ రూపొందించండి.',
  your_sets: 'మీ సెట్‌లు', no_sets: 'సెట్‌లు లేవు.', delete_set: 'సెట్ తొలగించండి', cards_count: 'కార్డులు',
  generate_new_set: 'కొత్త సెట్ రూపొందించండి', set_title: 'సెట్ శీర్షిక', topic_optional: 'అంశం (ఐచ్ఛికం)',
  paste_text: 'టెక్స్ట్ పేస్ట్ చేయండి', generate_magic: 'మ్యాజిక్ రూపొందించండి', generating: 'రూపొందిస్తోంది…',
  cards_ready: 'కార్డులు సిద్ధంగా ఉన్నాయి', save_set_btn: 'సెట్ సేవ్ చేయండి',
  delete_confirm_flashcard: 'మీరు ఈ ఫ్లాష్‌కార్డ్ సెట్‌ను తొలగించాలనుకుంటున్నారా?',
  attendance: 'హాజరు', mark_attendance: 'హాజరు నమోదు చేయండి', register_student: 'విద్యార్థిని నమోదు చేయండి',
  records: 'రికార్డులు', manage_classes: 'తరగతులు నిర్వహించండి', scanning: 'స్కాన్ అవుతోంది…',
  capture_btn: 'క్యాప్చర్ చేసి హాజరు నమోదు చేయండి', processing: 'ప్రాసెస్ అవుతోంది…',
  total_days: 'మొత్తం రోజులు', present: 'హాజరు', absent: 'గైర్హాజరు', attendance_pct: 'హాజరు %',
  select_class_section: 'తరగతి విభాగం ఎంచుకోండి', choose_class: '— తరగతి విభాగం ఎంచుకోండి —',
  no_classes_found: 'తరగతులు కనుగొనబడలేదు.', look_at_camera: 'కెమెరా వైపు చూసి క్యాప్చర్ చేయండి.',
  select_student: 'విద్యార్థిని ఎంచుకోండి', choose_student: '— నమోదైన విద్యార్థిని ఎంచుకోండి —',
  start_capture: 'క్యాప్చర్ ప్రారంభించండి', stop_recording: 'ఆపండి', upload_frames: 'ఫ్రేమ్‌లు అప్‌లోడ్ చేయండి',
  student_summary: 'విద్యార్థి సారాంశం', no_records_found: 'రికార్డులు కనుగొనబడలేదు.', loading_records: 'రికార్డులు లోడ్ అవుతున్నాయి…',
  scholarships: 'స్కాలర్‌షిప్‌లు', scholarships_title: 'స్కాలర్‌షిప్‌లతో మీ సామర్థ్యాన్ని వెలికితీయండి',
  scholarships_subtitle: 'విద్యార్థులకు ఆర్థిక సహాయ అవకాశాలు.',
  no_scholarships: 'ప్రస్తుతం స్కాలర్‌షిప్‌లు లేవు.',
  deadline: 'చివరి తేదీ', eligibility: 'అర్హత', amount: 'మొత్తం', apply_now: 'ఇప్పుడే దరఖాస్తు చేయండి',
  quiz_complete: 'క్విజ్ పూర్తయింది', your_score: 'మీ స్కోర్', back_to_dashboard: 'డాష్‌బోర్డ్‌కు తిరిగి వెళ్ళండి',
  view_quiz_details: 'క్విజ్ వివరాలు చూడండి', loading_quiz: 'క్విజ్ లోడ్ అవుతోంది…',
  submit_answers: 'సమాధానాలు సమర్పించండి', submitting: 'సమర్పిస్తోంది…', question_label: 'ప్రశ్న',
  questions_count: 'ప్రశ్నలు', time_limit: 'సమయ పరిమితి', start_quiz: 'క్విజ్ ప్రారంభించండి',
  quiz_completed_badge: 'క్విజ్ పూర్తయింది', already_attempted: 'మీరు ఈ క్విజ్‌ను ఇప్పటికే ప్రయత్నించారు.',
  loading_quiz_details: 'వివరాలు లోడ్ అవుతున్నాయి…', review: 'సమీక్ష',
};

// ── Marathi ───────────────────────────────────────────────────────────────────
const mr = {
  dashboard: 'मुख्यपृष्ठ', student_dashboard: 'विद्यार्थी मुख्यपृष्ठ', teacher_dashboard: 'शिक्षक मुख्यपृष्ठ',
  lectures: 'व्याख्याने', quizzes: 'प्रश्नमंजुषा', results: 'निकाल', flashcards: 'फ्लॅशकार्ड',
  digital_skills: 'डिजिटल कौशल्ये', logout: 'साइन आउट', welcome: 'पुन्हा स्वागत आहे',
  no_lectures: 'कोणतेही व्याख्यान नाही.', available_lectures: 'उपलब्ध व्याख्याने',
  download_lecture: 'व्याख्यान डाउनलोड करा', take_quiz: 'प्रश्नमंजुषा द्या', no_quizzes: 'कोणतीही प्रश्नमंजुषा नाही.',
  create_quiz: 'प्रश्नमंजुषा तयार करा', new_lecture: 'नवीन व्याख्यान अपलोड करा', title: 'शीर्षक', description: 'वर्णन',
  skills_desc: 'संगणक आणि इंटरनेट वापरणे शिका.', all: 'सर्व',
  computer_science: 'संगणक विज्ञान', mathematics: 'गणित',
  audio_resources: 'ऑडिओ व्याख्याने', document_resources: 'कागदपत्रे',
  no_videos_available: 'कोणतेही व्हिडिओ नाही.', teacher_name: 'शिक्षकाचे नाव',
  subscribers: 'सदस्य', published_on: 'प्रकाशित', no_description: 'कोणतेही वर्णन नाही',
  additional_resources: 'अतिरिक्त संसाधने', audio_lecture_tag: 'ऑडिओ व्याख्यान',
  document_file_tag: 'कागदपत्र/फाइल', download: 'डाउनलोड',
  results_title: 'तुमचे निकाल', results_subtitle: 'सर्व प्रयत्नांमध्ये कामगिरी ट्रॅक करा.',
  loading_results: 'निकाल लोड होत आहेत…', total_quizzes_attempted: 'एकूण प्रश्नमंजुषा प्रयत्न',
  total_submissions: 'एकूण सादरीकरणे', average_accuracy: 'सरासरी अचूकता',
  attempt_history: 'प्रयत्न इतिहास', no_attempts_results: 'अद्याप कोणतेही प्रयत्न नाहीत.',
  find_quizzes: 'प्रश्नमंजुषा शोधा', excellent: 'उत्कृष्ट', passed: 'उत्तीर्ण', needs_review: 'पुनरावलोकन आवश्यक',
  unknown_quiz: 'अज्ञात प्रश्नमंजुषा', questions_total: 'एकूण प्रश्न', score_uppercase: 'गुण',
  student_dashboard_subtitle: 'प्रश्नमंजुषा निवडा, व्याख्याने पहा.',
  available_quizzes: 'उपलब्ध प्रश्नमंजुषा', no_published_quizzes: 'कोणतीही प्रश्नमंजुषा नाही.',
  seconds_time_limit: 'सेकंद वेळ मर्यादा', recent_attempts: 'अलीकडील प्रयत्न', no_attempts_recent: 'कोणतेही प्रयत्न नाहीत.',
  quiz: 'प्रश्नमंजुषा', click_to_flip: 'उलटण्यासाठी क्लिक करा', answer: 'उत्तर',
  flashcards_title: 'फ्लॅशकार्ड', flashcards_subtitle: 'मजकुरातून संच तयार करा.',
  your_sets: 'तुमचे संच', no_sets: 'कोणतेही संच नाहीत.', delete_set: 'संच हटवा', cards_count: 'कार्डे',
  generate_new_set: 'नवीन संच तयार करा', set_title: 'संच शीर्षक', topic_optional: 'विषय (पर्यायी)',
  paste_text: 'मजकूर पेस्ट करा', generate_magic: 'जादू निर्माण करा', generating: 'निर्माण होत आहे…',
  cards_ready: 'कार्डे तयार', save_set_btn: 'संच जतन करा',
  delete_confirm_flashcard: 'तुम्हाला हा फ्लॅशकार्ड संच हटवायचा आहे का?',
  attendance: 'उपस्थिती', mark_attendance: 'उपस्थिती नोंदवा', register_student: 'विद्यार्थी नोंदणी करा',
  records: 'नोंदी', manage_classes: 'वर्ग व्यवस्थापित करा', scanning: 'स्कॅन होत आहे…',
  capture_btn: 'कॅप्चर करा आणि उपस्थिती नोंदवा', processing: 'प्रक्रिया होत आहे…',
  total_days: 'एकूण दिवस', present: 'उपस्थित', absent: 'अनुपस्थित', attendance_pct: 'उपस्थिती %',
  select_class_section: 'वर्ग विभाग निवडा', choose_class: '— वर्ग विभाग निवडा —',
  no_classes_found: 'कोणतेही वर्ग सापडले नाहीत.', look_at_camera: 'कॅमेऱ्याकडे पहा आणि कॅप्चर करा.',
  select_student: 'विद्यार्थी निवडा', choose_student: '— नोंदणीकृत विद्यार्थी निवडा —',
  start_capture: 'कॅप्चर सुरू करा', stop_recording: 'थांबा', upload_frames: 'फ्रेम अपलोड करा',
  student_summary: 'विद्यार्थी सारांश', no_records_found: 'कोणत्याही नोंदी सापडल्या नाहीत.', loading_records: 'नोंदी लोड होत आहेत…',
  scholarships: 'शिष्यवृत्ती', scholarships_title: 'शिष्यवृत्तीने तुमची क्षमता उघडा',
  scholarships_subtitle: 'शाळकरी विद्यार्थ्यांसाठी आर्थिक मदतीच्या संधी.',
  no_scholarships: 'सध्या कोणतीही शिष्यवृत्ती उपलब्ध नाही.',
  deadline: 'अंतिम तारीख', eligibility: 'पात्रता', amount: 'रक्कम', apply_now: 'आत्ता अर्ज करा',
  quiz_complete: 'प्रश्नमंजुषा पूर्ण', your_score: 'तुमचा गुण', back_to_dashboard: 'डॅशबोर्डवर परत',
  view_quiz_details: 'प्रश्नमंजुषा तपशील पहा', loading_quiz: 'प्रश्नमंजुषा लोड होत आहे…',
  submit_answers: 'उत्तरे सादर करा', submitting: 'सादर होत आहे…', question_label: 'प्रश्न',
  questions_count: 'प्रश्न', time_limit: 'वेळ मर्यादा', start_quiz: 'प्रश्नमंजुषा सुरू करा',
  quiz_completed_badge: 'प्रश्नमंजुषा पूर्ण', already_attempted: 'तुम्ही ही प्रश्नमंजुषा आधीच दिली आहे.',
  loading_quiz_details: 'तपशील लोड होत आहेत…', review: 'पुनरावलोकन',
};

// ── Tamil ─────────────────────────────────────────────────────────────────────
const ta = {
  dashboard: 'முகப்பு', student_dashboard: 'மாணவர் முகப்பு', teacher_dashboard: 'ஆசிரியர் முகப்பு',
  lectures: 'விரிவுரைகள்', quizzes: 'வினாடி வினா', results: 'முடிவுகள்', flashcards: 'ஃப்ளாஷ்கார்டுகள்',
  digital_skills: 'டிஜிட்டல் திறன்கள்', logout: 'வெளியேறு', welcome: 'மீண்டும் வரவேற்கிறோம்',
  no_lectures: 'விரிவுரைகள் இல்லை.', available_lectures: 'கிடைக்கும் விரிவுரைகள்',
  download_lecture: 'விரிவுரை பதிவிறக்கம்', take_quiz: 'வினாடி வினா எடு', no_quizzes: 'வினாடி வினா இல்லை.',
  create_quiz: 'வினாடி வினா உருவாக்கு', new_lecture: 'புதிய விரிவுரை பதிவேற்று', title: 'தலைப்பு', description: 'விளக்கம்',
  skills_desc: 'கணினி மற்றும் இணையம் பயன்படுத்த கற்றுக்கொள்ளுங்கள்.', all: 'அனைத்தும்',
  computer_science: 'கணினி அறிவியல்', mathematics: 'கணிதம்',
  audio_resources: 'ஆடியோ விரிவுரைகள்', document_resources: 'ஆவணங்கள்',
  no_videos_available: 'வீடியோக்கள் இல்லை.', teacher_name: 'ஆசிரியர் பெயர்',
  subscribers: 'சந்தாதாரர்கள்', published_on: 'வெளியிடப்பட்டது', no_description: 'விளக்கம் இல்லை',
  additional_resources: 'கூடுதல் வளங்கள்', audio_lecture_tag: 'ஆடியோ விரிவுரை',
  document_file_tag: 'ஆவணம்/கோப்பு', download: 'பதிவிறக்கம்',
  results_title: 'உங்கள் முடிவுகள்', results_subtitle: 'உங்கள் செயல்திறனை கண்காணிக்கவும்.',
  loading_results: 'முடிவுகள் ஏற்றப்படுகின்றன…', total_quizzes_attempted: 'மொத்த வினாடி வினா முயற்சிகள்',
  total_submissions: 'மொத்த சமர்ப்பிப்புகள்', average_accuracy: 'சராசரி துல்லியம்',
  attempt_history: 'முயற்சி வரலாறு', no_attempts_results: 'இன்னும் முயற்சிகள் இல்லை.',
  find_quizzes: 'வினாடி வினா கண்டுபிடி', excellent: 'சிறப்பானது', passed: 'தேர்ச்சி', needs_review: 'மதிப்பாய்வு தேவை',
  unknown_quiz: 'தெரியாத வினாடி வினா', questions_total: 'மொத்த கேள்விகள்', score_uppercase: 'மதிப்பெண்',
  student_dashboard_subtitle: 'வினாடி வினா தேர்ந்தெடு, விரிவுரைகள் பார்.',
  available_quizzes: 'கிடைக்கும் வினாடி வினா', no_published_quizzes: 'வினாடி வினா இல்லை.',
  seconds_time_limit: 'வினாடி நேர வரம்பு', recent_attempts: 'சமீபத்திய முயற்சிகள்', no_attempts_recent: 'முயற்சிகள் இல்லை.',
  quiz: 'வினாடி வினா', click_to_flip: 'திருப்ப கிளிக் செய்யவும்', answer: 'பதில்',
  flashcards_title: 'ஃப்ளாஷ்கார்டுகள்', flashcards_subtitle: 'உரையிலிருந்து தொகுப்பை உருவாக்கவும்.',
  your_sets: 'உங்கள் தொகுப்புகள்', no_sets: 'தொகுப்புகள் இல்லை.', delete_set: 'தொகுப்பை நீக்கு', cards_count: 'அட்டைகள்',
  generate_new_set: 'புதிய தொகுப்பை உருவாக்கு', set_title: 'தொகுப்பு தலைப்பு', topic_optional: 'தலைப்பு (விருப்பத்தேர்வு)',
  paste_text: 'உரையை ஒட்டவும்', generate_magic: 'மாயம் உருவாக்கு', generating: 'உருவாக்கப்படுகிறது…',
  cards_ready: 'அட்டைகள் தயார்', save_set_btn: 'தொகுப்பை சேமி',
  delete_confirm_flashcard: 'இந்த ஃப்ளாஷ்கார்டு தொகுப்பை நீக்க விரும்புகிறீர்களா?',
  attendance: 'வருகை', mark_attendance: 'வருகை பதிவு செய்', register_student: 'மாணவரை பதிவு செய்',
  records: 'பதிவுகள்', manage_classes: 'வகுப்புகளை நிர்வகி', scanning: 'ஸ்கேன் செய்யப்படுகிறது…',
  capture_btn: 'படம் எடுத்து வருகை பதிவு செய்', processing: 'செயலாக்கப்படுகிறது…',
  total_days: 'மொத்த நாட்கள்', present: 'வருகை', absent: 'வருகையில்லை', attendance_pct: 'வருகை %',
  select_class_section: 'வகுப்பு பிரிவை தேர்ந்தெடு', choose_class: '— வகுப்பு பிரிவை தேர்ந்தெடு —',
  no_classes_found: 'வகுப்புகள் இல்லை.', look_at_camera: 'கேமராவை நோக்கி பாருங்கள் மற்றும் படம் எடுங்கள்.',
  select_student: 'மாணவரை தேர்ந்தெடு', choose_student: '— பதிவு செய்யப்பட்ட மாணவரை தேர்ந்தெடு —',
  start_capture: 'படம் எடுக்க தொடங்கு', stop_recording: 'நிறுத்து', upload_frames: 'ஃப்ரேம்களை பதிவேற்று',
  student_summary: 'மாணவர் சுருக்கம்', no_records_found: 'பதிவுகள் இல்லை.', loading_records: 'பதிவுகள் ஏற்றப்படுகின்றன…',
  scholarships: 'உதவித்தொகைகள்', scholarships_title: 'உதவித்தொகைகளால் உங்கள் திறனை வெளிப்படுத்துங்கள்',
  scholarships_subtitle: 'பள்ளி மாணவர்களுக்கான நிதி உதவி வாய்ப்புகள்.',
  no_scholarships: 'தற்போது உதவித்தொகைகள் இல்லை.',
  deadline: 'கடைசி தேதி', eligibility: 'தகுதி', amount: 'தொகை', apply_now: 'இப்போதே விண்ணப்பிக்கவும்',
  quiz_complete: 'வினாடி வினா முடிந்தது', your_score: 'உங்கள் மதிப்பெண்', back_to_dashboard: 'டாஷ்போர்டுக்கு திரும்பு',
  view_quiz_details: 'வினாடி வினா விவரங்கள் பார்', loading_quiz: 'வினாடி வினா ஏற்றப்படுகிறது…',
  submit_answers: 'பதில்களை சமர்ப்பி', submitting: 'சமர்ப்பிக்கப்படுகிறது…', question_label: 'கேள்வி',
  questions_count: 'கேள்விகள்', time_limit: 'நேர வரம்பு', start_quiz: 'வினாடி வினா தொடங்கு',
  quiz_completed_badge: 'வினாடி வினா முடிந்தது', already_attempted: 'நீங்கள் ஏற்கனவே இந்த வினாடி வினாவை முயற்சித்தீர்கள்.',
  loading_quiz_details: 'விவரங்கள் ஏற்றப்படுகின்றன…', review: 'மதிப்பாய்வு',
};

const translations = { en, hi, pa, bn, te, mr, ta };

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try {
      return localStorage.getItem('lang') || 'en';
    } catch {
      return 'en';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('lang', lang);
    } catch {
      // ignore storage errors (private mode / restricted env)
    }
  }, [lang]);

  const dict = translations[lang] || translations.en;
  const t = (key) => dict?.[key] ?? translations.en?.[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return ctx;
}
